### ISSUE TITLE
Can this plugin support older version of idea?

### ISSUE THREAD

**Issue by momadacoding** [Mishkun/ideavim-sneak#22]
I use pycharm 2018.3.7 pro, because I only has this liscense, I like this plugin, it's more suitable for me rather than easy-motion plugin, but I can't install it in my older version of pycharm sadly 😢

**Comment by Mishkun** [comment]
I think that there is no obstacles of this working with older versions of idea. I will try to update it asap.

**Comment by momadacoding** [comment]
> I think that there is no obstacles of this working with older versions of idea. I will try to update it asap.

Is there any thing I can help?

**Comment by Mishkun** [comment]
I published version 1.2.1. It should hit in two buisness days after Jetbrains Marketplace verification

**Comment by Mishkun** [comment]
@haolly Unfortunately, 1.2.1 won't pass Intellij Ultimate compatablity check and thus cannot be published in Jetbrains Marketplace. You can still try to sideload this build manually.

- download zip with plugin from releases (or build it yourself using `./gradlew assemble`) https://github.com/Mishkun/ideavim-sneak/releases/tag/1.2.1
- follow the instructions about installing plugin from disk https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by momadacoding** [comment]
thanks, @Mishkun   I have downloaded the zip and install it from disk, but it has exceptions:
java.lang.NoClassDefFoundError: com/maddyhome/idea/vim/VimProjectService
	at io.github.mishkun.ideavimsneak.IdeaVimSneakExtension$HighlightHandler.highlightSneakRange(IdeaVimSneakExtension.kt:186)
	at io.github.mishkun.ideavimsneak.IdeaVimSneakExtension$SneakHandler.execute(IdeaVimSneakExtension.kt:70)
	at com.maddyhome.idea.vim.KeyHandler.lambda$handleCompleteMappingSequence$4(KeyHandler.java:465)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.maddyhome.idea.vim.KeyHandler.handleCompleteMappingSequence(KeyHandler.java:465)
	at com.maddyhome.idea.vim.KeyHandler.handleKeyMapping(KeyHandler.java:354)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:215)
	at com.maddyhome.idea.vim.KeyHandler.handleCompleteMappingSequence(KeyHandler.java:445)
	at com.maddyhome.idea.vim.KeyHandler.handleKeyMapping(KeyHandler.java:354)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:215)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:170)
	at com.maddyhome.idea.vim.VimTypedActionHandler.execute(VimTypedActionHandler.kt:53)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$0(TypedAction.java:130)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:42)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:130)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1238)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1223)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3293)
	at com.intellij.openapi.editor.impl.EditorImpl$7.keyTyped(EditorImpl.java:1053)
	at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:239)
	at java.awt.Component.processKeyEvent(Component.java:6503)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2833)
	at java.awt.Component.processEvent(Component.java:6325)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4774)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.maddyhome.idea.vim.VimProjectService PluginClassLoader[io.github.mishkun.ideavimsneak, 1.2.1] com.intellij.ide.plugins.cl.PluginClassLoader@7d58a5f0
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 61 more


---------------------------------
Also I have found that ideavim easymotion support multiple char match, so I have switched to using it.
The exception post here for you in cause there are some bugs in code , which can help you to investigate

**Comment by Mishkun** [comment]
Unfortunately, this is a compatability issue, I cannot do much about that =(
